#
# Nmake file - For MS Visual C++ version
# Use 'nmake -f Makefile.win'

all: 
	cd libmseed
	nmake -f Makefile.win
	cd ..\src
	nmake -f Makefile.win
	cd ..

clean:
	cd libmseed
	nmake -f Makefile.win clean
	cd ..\src
	nmake -f Makefile.win clean
	cd ..
