.TH MS_FIND_RECLEN 3 2006/04/20 "Libmseed API"
.SH DESCRIPTION
Determine SEED record data length

.SH SYNOPSIS
.nf
.B #include <libmseed.h>

.BI "int  \fBms_find_reclen\fP ( const char *" recbuf ", int " recbuflen ",
.BI "                            FILE " *fileptr " );
.fi

.SH DESCRIPTION
\fBms_find_reclen\fP verifies that the specified \fIrecbuf\fP buffer
contains a SEED data record by looking for data record signatures in
the fixed section data header and determines the data record length by
1) searching the buffer up to \fIrecbuflen\fP bytes for a Blockette
1000 and 2) if \fIfileptr\fP is not NULL reading the next 48 bytes
from the file and looking for a data record signature (with detection
of the next data record implying the length of the current record).
If data is read from \fIfileptr\fP the read position is returned to
it's position prior to this function call.

To verify that the buffer contains a SEED data record the routine
checks that it starts with 6 ASCII characters (the sequence
number) followed by a valid data record indicator (D, R or Q) followed
by a space character.

.SH RETURN VALUES
\fBms_find_reclen\fP returns the length of the Mini-SEED record in
bytes or 0 if a data record was detected but the length could not be
determined or -1 when no data record was detected.

If a data record is found but no record length could be determined
(return of 0) this means that no Blockette 1000 was found in the
buffer and, if \fIfileptr\fP is not NULL, no data record header was
found in the next 48 bytes of the file.

.SH SEE ALSO
\fBms_readmsr(3)\fP, \fBms_readtraces(3)\fP and \fBmsr_unpack(3)\fP.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
