.TH MS_FIND_RECLEN 3 2005/12/01 "Libmseed API"
.SH DESCRIPTION
Perform simple SEED data record verification, search for a
Blockette 1000 and return the record size.

.SH SYNOPSIS
.nf
.B #include <libmseed.h>

.BI "int  \fBms_find_reclen\fP ( const char *" msrecord ", int " maxheaderlen " );"
.fi

.SH DESCRIPTION
\fBms_find_reclen\fP verifies the specified \fImsrecord\fP buffer
contains a SEED data record, searches the record up to
\fImaxheaderlen\fP bytes for a Blockette 1000 and determines the
record length.

To verify that the buffer contains a SEED data record the routine
checks that it starts with 6 ASCII characters (the sequence
number) followed by a valid data record indicator (D, R or Q) followed
by a space character.

A Mini-SEED record is, by definition, a data record that includes a
Blockette 1000.  This routine will not be able to determine the record
length of a plain SEED data record that does not include a Blockette
1000.

.SH RETURN VALUES
\fBms_find_reclen\fP returns the length of the Mini-SEED record in
bytes or 0 if a data record was detected but no Blockette 1000 was
found or -1 when no data record was detected.

.SH SEE ALSO
\fBms_readmsr(3)\fP, \fBms_readtraces(3)\fP and \fBmsr_unpack(3)\fP.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
