.TH MSR_PRINT 3 2004/11/22 "Libmseed API"
.SH DESCRIPTION
Printing of Mini-SEED record header values.

.SH SYNOPSIS
.nf
.B #include <libmseed.h>

.BI "void   \fBmsr_print\fP ( MSrecord *" msr ", flag " details " );

.BI "char  *\fBmsr_srcname\fP ( MSrecord *" msr ", char *" srcname " );
.fi

.SH DESCRIPTION
\fBmsr_print\fP prints formatted details from the given (parsed)
record header, i.e. fixed section and blockettes, to stdout.  The
\fIdetails\fP flag controls how much information is printed:
.nf
0  : a single line summarizing the record
1  : most commonly desired header details
2+ : all header details
.fi

If no fixed section header information is available at MSrecord.fsdh
then a single line is printed from the other information in the
MSrecord structure.

\fBmsr_srcname\fP generates a source name string in the
format: 'NET_STA_LOC_CHAN' and stores it in \fIsrcname\fP.  The memory
pointed to by \fIsrcname\fP must have enough room for the resulting
string.

.SH RETURN VALUES
\fBmsr_srcname\fP returns a pointer to the resulting string or NULL on
error.

.SH SEE ALSO
\fBms_intro(3)\fP and \fBmsr_unpack(3)\fP.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
