.TH SAC2MSEED 1 2006/02/20
.SH NAME
SAC to Mini-SEED converter

.SH SYNOPSIS
.nf
sac2mseed [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBsac2mseed\fP converts SAC waveform data to Mini-SEED format.  By
default the format of the input files is automatically detected: alpha
or binary (byte order autodetected).  The format can also be forced
with the \fI-f\fP option.  If an input file name is prefixed with an '@'
character the file is assumed to contain a list of input data files,
see \fILIST FILES\fP below.

If the input file name ends in ".sac" (not case sensitive) the default
output file name will be the same with the extension replace with
".mseed".  The output data may be re-directed to a single file or
stdout using the -o option.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-S         "
Include SEED blockette 100 in each output record with the sample rate
in floating point format.  The basic format for storing sample rates
in SEED data records is a rational approximation
(numerator/denominator).  Precision will be lost if a given sample
rate cannot be well approximated.  This option should be used in those
cases.

.IP "-n \fInetcode\fP"
Specify the SEED network code to use, if not specified the network
code will be blank.  It is highly recommended to specify a network
code.

.IP "-l \fIloccode\fP"
Specify the SEED location code to use, if not specified the location
code will be blank.

.IP "-r \fIbytes\fP"
Specify the Mini-SEED record length in \fIbytes\fP, default is 4096.

.IP "-e \fIencoding\fP"
Specify the Mini-SEED data encoding format, default is 11 (Steim-2
compression).  Other supported encoding formats include 10 (Steim-1
compression), 1 (16-bit integers) and 3 (32-bit integers).  The 16-bit
integers encoding should only be used if all data samples can be
represented in 16 bits.

.IP "-b \fIbyteorder\fP"
Specify the Mini-SEED byte order, default is 1 (big-endian or most
significant byte first).  The other option is 0 (little-endian or
least significant byte first).  It is highly recommended to always
create big-endian SEED.

.IP "-o \fIoutfile\fP"
Write all Mini-SEED records to \fIoutfile\fP, if \fIoutfile\fP is a
single dash (-) then all Mini-SEED output will go to stdout.  All
diagnostic output from the program is written to stderr and should
never get mixed with data going to stdout.

.IP "-s \fIfactor\fP"
When writing data to an integer (Mini-SEED) encoding format apply this
scaling \fIfactor\fP to each input floating point data sample before
truncating to an integer.  By default autoscaling is used and a
scaling factor is determined that will scale the maximum sample value
to a minimum of 6 digits.  If none of the input sample values include
fractional components the scaling factor will be 1 and the floating
point data will simply be truncated to their integer components.

.IP "-f \fIformat\fP"
By default the format of each input file is autodetected, either alpha
or binary (little or big endian byte order autodetected as well).
This option forces the format for every input file:

.nf
0 : Autodetect SAC format (default)
1 : Alphanumeric SAC format
2 : Binary SAC format, autodetect byte order
3 : Binary SAC format, little-endian
4 : Binary SAC format, big-endian
.fi

.SH LIST FILES
If an input file is prefixed with an '@' character the file is assumed
to contain a list of file for input.  Multiple list files can be
combined with multiple input files on the command line.  The last,
space separated field on each line is assumed to be the file name to
be read.

An example of a simple text list:

.nf
2003-06-20-0643-41S.EDI___003
2005-07-23-1452-04S.CER___030
.fi

.SH ABOUT SAC
Seismic Analysis Code (SAC) is a general purpose interactive program
designed for the study of sequential signals, especially timeseries
data.  Originally developed at the Lawrence Livermore National
Laboratory the SAC software package is also available from IRIS.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
