.TH MSEED2SAC 1 2011/01/25
.SH NAME
Mini-SEED to SAC converter

.SH SYNOPSIS
.nf
mseed2sac [options] file1 [file2 file3 ...]

.fi
.SH DESCRIPTION
\fBmseed2sac\fP converts Mini-SEED waveform data to SAC format.  The
output SAC file can be either ASCII or binary (either byte-order), the
default is binary with the same byte-order as the host computer.  By
default all aspects of the input files are automatically detected.  If
an input file name is prefixed with an '@' character the file is
assumed to contain a list of input data files, see \fILIST FILES\fP
below.

A separate output file is written for each continuous time-series in
the input data.  Output file names are of the form:

.nf
"Net.Sta.Loc.Chan.Qual.YYYY,DDD,HH:MM:SS.SAC"

For example:
"TA.ELFS..LHZ.R.2006,123,15:36:19.SAC"
.fi

If the input file name is "-" input Mini-SEED records will be read
from standard input.

The SAC header variable KHOLE is used synonymously with the SEED
location code.  Any location codes found in the input Mini-SEED or
metadata file are put into the KHOLE variable.

.SH OPTIONS

.IP "-V         "
Print program version and exit.

.IP "-h         "
Print program usage and exit.

.IP "-v         "
Be more verbose.  This flag can be used multiple times ("-v -v" or
"-vv") for more verbosity.

.IP "-n \fInetcode\fP"
Specify the network code to use, overriding any network code in the
input Mini-SEED.

.IP "-s \fIstation\fP"
Specify the station code to use, overriding any station code in the
input Mini-SEED.

.IP "-l \fIlocation\fP"
Specify the location code to use, overriding any location code in the
input Mini-SEED.

.IP "-c \fIchannel\fP"
Specify the channel code to use, overriding any channel code in the
input Mini-SEED.

.IP "-r \fIbytes\fP"
Specify the Mini-SEED record length in \fIbytes\fP, by default this is
autodetected.

.IP "-i         "
Process each input file individually.  By default all input files are
read and all data is buffered in memory before SAC files are written.
This allows time-series spanning mutilple input files to be merged and
written in a single SAC file.  The intention is to use this option
when processing large amounts of data in order to keep memory usage
within reasonable limits.

.IP "-k \fIlat/lon\fP"
Specify coordinates to put into the resulting SAC file(s).  The
argument format is "Latitude/Longitude" e.g. "47.66/-122.31".
Coordinates specified with this option override any coordinates found
in the metadata file.

.IP "-m \fImetafile\fP"
Specify a file containing metadata such as coordinates, elevation,
component orientation, scaling factor, etc.  For each time-series
written any matching metadata will be added to the SAC header.  see
\fIMETADATA FILES\fP below.

.IP "-msi       "
Convert any component inclination values in a metadata file from SEED
(dip) to SAC convention, this is a simple matter of adding 90 degrees.

.IP "-E \fIevent\fP"
Specify event parameters to add to the SAC file in the following
format:

.nf
"Time[/Lat][/Lon][/Depth][/Name]"

For example:
"2006,123,15:27:08.7/-20.33/-174.03/65.5/Tonga"
.fi

The parameters later in the string are optional.

.IP "-f \fIformat\fP"
The default output format is binary SAC with the same byte order as
the host computer.  This option forces the format for every output
file:

.nf
1 : Alphanumeric SAC format
2 : Binary SAC format, host byte order (default)
3 : Binary SAC format, little-endian
4 : Binary SAC format, big-endian
.fi

.SH METADATA FILES
A metadata file contains a list of station parameters, some of which
can be stored in SAC but not in Mini-SEED.  Each line in a metadata
file should be a comma-separated list of parameters in the following
order:

.nf
Network (KNETWK)
Station (KSTNM)
Location (KHOLE)
Channel (KCMPNM)
Latitude (STLA)
Longitude (STLO)
Elevation (STEL), in meters [not currently used by SAC]
Depth (STDP), in meters [not currently used by SAC]
Component Azimuth (CMPAZ), degrees clockwise from north
Component Incident Angle (CMPINC), degrees from vertical
Instrument Name (KINST), up to 8 characters
Scale Factor (SCALE)
Scale Frequency, unused
Scale Units, unused
Sampling rate, unused
Start time, used for matching
End time, used for matching


For example:
------------------
#net,sta,loc,chan,lat,lon,elev,depth,azimuth,SACdip,instrument,scale,scalefreq,scaleunits,samplerate,start,end
IU,ANMO,00,BH1,34.945981,-106.457133,1671,145,328,90,Geotech KS-54000,3456610000,0.02,M/S,20,2008-06-30T20:00:00,2599-12-31T23:59:59
IU,ANMO,00,BH2,34.945981,-106.457133,1671,145,58,90,Geotech KS-54000,3344370000,0.02,M/S,20,2008-06-30T20:00:00,2599-12-31T23:59:59
IU,ANMO,00,BHZ,34.945981,-106.457133,1671,145,0,0,Geotech KS-54000,3275080000,0.02,M/S,20,2008-06-30T20:00:00,2599-12-31T23:59:59
IU,ANMO,10,BH1,34.945913,-106.457122,1767.2,48.8,64,90,Guralp CMG3-T,32805600000,0.02,M/S,40,2008-06-30T20:00:00,2599-12-31T23:59:59
IU,ANMO,10,BH2,34.945913,-106.457122,1767.2,48.8,154,90,Guralp CMG3-T,32655000000,0.02,M/S,40,2008-06-30T20:00:00,2599-12-31T23:59:59
IU,ANMO,10,BHZ,34.945913,-106.457122,1767.2,48.8,0,0,Guralp CMG3-T,33067200000,0.02,M/S,40,2008-06-30T20:00:00,2599-12-31T23:59:59
------------------

As a special case '--' can be used to match a blank (space, space)
location code.
.fi

For each time-series written, metadata from the first line with
matching source name parameters (network, station, location and
channel) and time window (if specified) will be inserted into the SAC
header.  All parameters are optional except for the first four fields
specifying the source name parameters.

Simple wildcarding: for the source name parameters that will be
matched a '*' character in a field will match anything.  The BHZ
metadata lines above, for example, can be (almost) summarized as:

.nf
IU,ANMO,*,BHZ,34.9459,-106.4571,1671,145,0,0,Geotech KS-54000,3456610000,0.02,M/S,20,2008-06-30T20:00:00,2599-12-31T23:59:59
.fi


.SH LIST FILES
If an input file is prefixed with an '@' character the file is assumed
to contain a list of file for input.  Multiple list files can be
combined with multiple input files on the command line.  The last,
space separated field on each line is assumed to be the file name to
be read.

An example of a simple text list:

.nf
TA.ELFS..LHE.R.mseed
TA.ELFS..LHN.R.mseed
TA.ELFS..LHZ.R.mseed
.fi

.SH ABOUT SAC
Seismic Analysis Code (SAC) is a general purpose interactive program
designed for the study of sequential signals, especially timeseries
data.  Originally developed at the Lawrence Livermore National
Laboratory the SAC software package is also available from IRIS.

.SH AUTHOR
.nf
Chad Trabant
IRIS Data Management Center
.fi
